python:
  - 3.4
  - 3.5
install:
  - pip install -r test-requirements.txt
script:
  - flake8 . --max-line-length=85 --exclude=.svn,CVS,.bzr,.hg,.git,__pycache__,.tox,.eggs,*.egg,doc
  - pytest --cov=mwbase -m "not nottravis"
after_success:
  - codecov

